# Generated by Django 3.1.5 on 2021-03-04 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chefs_image/', verbose_name='Chef rasmi')),
                ('name', models.CharField(max_length=100, verbose_name='Chef ismi')),
                ('body', models.TextField(verbose_name='Malumot')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Taom nomi')),
                ('body', models.TextField(verbose_name="Taomga ta'rif")),
                ('image', models.ImageField(upload_to='order_food/', verbose_name='Taom rasmi')),
                ('cost', models.CharField(max_length=10, verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
            },
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('number', models.CharField(max_length=15, verbose_name='Tel raqami')),
                ('date', models.CharField(max_length=30, verbose_name='Sanasi')),
                ('guass', models.CharField(max_length=3, verbose_name='Mehmon soni')),
                ('time_from', models.CharField(max_length=6, verbose_name='Gacha')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderfood',
            options={'verbose_name': 'Byurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='body',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='title',
        ),
        migrations.AddField(
            model_name='orderfood',
            name='name',
            field=models.CharField(default=111, max_length=100, verbose_name='Ismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfood',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='Tel raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfood',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Familyasi'),
            preserve_default=False,
        ),
    ]
