# Generated by Django 3.1.5 on 2021-03-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood_app', '0003_auto_20210304_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='guast',
            new_name='guest',
        ),
    ]
