# Generated by Django 3.1.5 on 2021-03-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood_app', '0004_auto_20210304_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeorder',
            options={'verbose_name': 'Joy Byurtma', 'verbose_name_plural': 'Joy Buyurtmalar'},
        ),
    ]
